### ISSUE TITLE
Disk with radius zero?

### ISSUE THREAD

**Issue by StefanSalewski** [vdrc/The-Source-Code-and-Benchmark-Dataset-for-QuickhullDisk#1]
Is your code intended to work when some or all disk have radius zero?

This 4 point file seems to crash your code:

```
cat N4.txt 
4
1 1.0 2.0 0.0
2 -1.0 2.0 0.0
3 -1.2 2.2 0.0
4 3.0 5.0 0.0

 ./RunQuickhullDisk -i N4.txt -o N4.out
1. Input arguments
 Input file: N4.txt
 Output file: N4.out

2. Input disks
 #Input disks: 4

Segmentation fault (core dumped)
```

Well all disk radius zero may sound stupid, as we could use a plain algorithm for points then. But some points may have zero radius, and generally it would be nice not crashing at all.

Some weeks ago I read your paper and was happy that the C++ code is available, as it is a bit hard to get all the math right following the paper. I did a plain conversion of your C++ code to Nim, which I will upload to github soon.

**Comment by simonryu** [comment]
Thank you for your interest and feedback. The code is updated. Now, you can input disk with radius zero.

**Comment by StefanSalewski** [comment]
Thank you very much! I have to admit that I had no idea where exactly the problem with radius zero resulted from, so debugging would have took me some time at least.

Great that you could fixed it!

**Comment by StefanSalewski** [comment]
I have just uploaded the Nim version of your C++ implementation including the latest fix:

https://github.com/StefanSalewski/QuickhullDisk

So I think we can close this issue.
